# -*- coding: utf-8 -*-
"""gradedLab01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GjoP5R1LUVtwlx9lmJ2il8bfxsLEGxXj

# **Import Libraries**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

"""#**Import CSV fiie**"""

df = pd.read_csv("titanic.csv")

df.head()

df = df.dropna()

x = df[['Age','Fare']]
y = df["Survived"]

"""#**Visualization of Dataset**"""

df["Age"] = df["Age"].fillna(30)
x= df[["Age","Fare"]]
fig = px.scatter_3d(df, x = 'Age' , y = 'Fare' , z = 'Survived')
fig.show()

"""#**Model Generation**"""

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.15)

"""#**Model: Logistic Regression**


**1.  Training**


"""

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train)

"""**2. Accuracy**"""

from sklearn.metrics import accuracy_score
y_predict = model.predict(x_test)
print(accuracy_score(y_predict,y_test))

"""**3.  Testing**"""

person_1 = np.array([[26,7.925]])

print(model.predict(person_1))

person_2 = np.array([[28,7.25]])
print(model.predict(person_2))

person_3 = np.array([[59,53.1]])
print(model.predict(person_3))